### ISSUE TITLE
Writing checklist

### ISSUE THREAD

**Issue by Bender250** [Bender250/eth_knowledge_base#2]
### Whole paper checklist

- [ ] Structural editing
  - [ ] general outline *(Does the content follow a logical flow?)*
  - [ ] figures - text alignment and linkage *(Are all figures consistently labeled and properly addressed in the paper?)*
- [ ] Proofreading
  - [ ] check clarity
    - [ ] simple comparisons
  - [ ] mistakes
  - [ ] grammar issues
    - [ ] tenses
    - [ ] commas
    - [ ] misplaced/dangling modifiers
    - [ ] problems with relative clauses
    - [ ] articles
    - [ ] others? your personal list? TODO
- [ ] Re-reading for improvement
  - [ ] eliminating redundancy
  - [ ] finding better wording
  - [ ] improving vocabulary
  - [ ] keep your reader in mind *(What is your reader likely to know or not know already? What is your reader likely to expect you to include in each section? )*
  - [ ] read abstract, intro and conclusion *(Re-read the introduction and then the conclusion to be sure you have addressed all the concerns and questions you raised)*
- [ ] Related work
  - [ ] unified tense
  - [ ] unified structure
  - [ ] refresh URLs before submission
  - [ ] format check

### Section-level checklist

- [ ] key sentences of each section *(Can you identify the key sentences in each section that emphasize the most important pieces of information you want your reader to remember? (Are they well-written and well-placed?))*
- [ ] order of definitions + usages
- [ ] missing content of section *(Does each section contain what it needs to contain in terms of content?)*
- [ ] structural repetition *(Do you repeat content only when necessary?)*

### Paragraph-level checklist
- [ ] paragraph outline flow *(Are paragraphs organized appropriately and in the appropriate order?)*
  - [ ] flow *(Read the first and last sentences of each paragraph to see if the flow is logical and transitions work.)*
  - [ ] outline paragraph for the sentence needed *(David: explain the big picture.)*
  - [ ] transition between paragraphs *(Are there transitions between topics when necessary and/or links between paragraphs?)*
  - [ ] common paragraph structure *(In cases where your paragraphs have a different internal structure (ie. chronological, general to specific, etc.), do you stick to it?)*
- [ ] individual paragraph checks
  - [ ] *(Does each paragraph have a clear, unified topic to which all sentences in the paragraph stick?)*
  - [ ] *(Is this topic clearly expressed or made obvious in the first 1 – 2 sentences of the paragraph?)*
  - [ ] search for paragraphs that are too long (>1/2 column length)/too short (3 sentences) *(Do any of your paragraphs contain less than 3 sentences? Are they typically longer than ½ of a typed page (200 words)? If so, can they be re-organized or are the atypical lengths justified?)*

### Sentence-level checklist

- [ ] Simple (check every time)
  - [ ] Length (15 – 25 words is average)
  - [ ] Subject – Verb – Object is typical order
  - [ ] Limit compound sentences (full sentences linked with and, or, but, etc.) and “front loaded” sentences and/or vary the structures
  - [ ] Parallelism: check lists of nouns, adjectives, phrases, etc.
  - [ ] Avoid needless formality and complexity 
  - [ ] Limit passive voice (approximately 25% passive as a guideline, for cases where action and not agent are important)
  - [ ] Use verbs rather than verbal nouns (ex. “The study analyses…”)
  - [ ] Use negative formulations only when necessary (not only… but also)
  - [ ] Put old information before new information in your sentences
  - [ ] Try to make the subject the actor and the verb the action in the sentence
  - [ ] Make sure that readers can easily locate key sentences in your work that express important main ideas for them to remember!

- [ ] Advanced
  - [ ] Subject + verb could have come sooner (ie. active verb could have been used or subject could have been shortened).
  - [ ] Sentence contains repeated or otherwise unnecessary words, phrases, or ideas (redundancy and/or nominalization)
  - [ ] Phrases or ideas are introduced without clear link to the previous material
  - [ ] Sentences contains components whose relationship to each other is either unclear to the reader (ie. dangling modifiers) or is not ideal (ie. parallel construction needed)
